# Generated by Django 5.0.4 on 2024-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('nacimiento', models.IntegerField()),
                ('fallecimiento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
