# Generated by Django 5.0.4 on 2024-04-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calificacion_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateField()),
                ('edicion', models.CharField(max_length=30)),
                ('costo', models.FloatField()),
                ('precio_venta_sugerido', models.FloatField()),
                ('disponible', models.BooleanField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calificacion')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editora')),
            ],
        ),
    ]
