# Generated by Django 5.0.4 on 2024-04-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.calificacion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.editora'),
        ),
    ]
